version: '3.7'
services:
  currency-exchange-service:
    image: lalitrnagpal/18-currency-exchange-service:0.0.1-SNAPSHOT
    ports:
      - "9000:9000"
    restart: always
    networks:
      - currency-compose-network

  currency-conversion-service:
    image: lalitrnagpal/18-currency-conversion-service:0.0.1-SNAPSHOT
    ports:
      - "9100:9100"
    restart: always
    environment:
      CURRENCY_EXCHANGE_URI: http://currency-exchange-service:9000
    depends_on:
      - currency-exchange-service
    networks:
      - currency-compose-network
  
# Networks to be created to facilitate communication between containers
networks:
  currency-compose-network: