version: '3'
services:
   redis-server:
      image: 'redis'
      ports:
         - '6379:6379'      
   java-app:
      build: .
      restart: always
      expose:
         - '9000'
   nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - java-app
      ports:
        - "4000:4000"