version: '3.7'
services:

  naming-server:
    image: lalitrnagpal/20-netflix-eureka-naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    restart: always
    networks:
      - currency-compose-network

  zuul-api-gateway:
    image: lalitrnagpal/20-netflix-zuul-api-gateway-server:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    restart: always
    depends_on:
      - naming-server
    networks:
      - currency-compose-network

  currency-exchange-service:
    image: lalitrnagpal/20-currency-exchange-service:0.0.1-SNAPSHOT
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - naming-server
    networks:
      - currency-compose-network

  currency-conversion-service:
    image: lalitrnagpal/20-currency-conversion-service:0.0.1-SNAPSHOT
    ports:
      - "9100:9100"
    restart: always
    environment:
      CURRENCY_EXCHANGE_URI: http://currency-exchange-service:9000
    depends_on:
      - currency-exchange-service
      - naming-server
    networks:
      - currency-compose-network
  
# Networks to be created to facilitate communication between containers
networks:
  currency-compose-network: